// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using health_index_app.Server.Data;

#nullable disable

namespace health_index_app.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230424014243_UpdateMealFoodFKAndSeedData")]
    partial class UpdateMealFoodFKAndSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.Key", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DataProtected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsX509Certificate")
                        .HasColumnType("bit");

                    b.Property<string>("Use")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Use");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("ConsumedTime");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants", (string)null);
                });

            modelBuilder.Entity("health_index_app.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ParentId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "93513a22-cecd-4bdc-ae16-c0dd5c95e4e9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "149454b4-2612-4bea-bf88-c61cf145bc8d",
                            Email = "eric@cognizant.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ERIC@COGNIZANT.COM",
                            NormalizedUserName = "ERIC@COGNIZANT.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEN56X+Sw/ByTCkcypT8NIDH4TlxK8e9hMaqWiq5T1OrKzb8N3ZY+RIKy7sCLLDP44A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d1e80a88-c41a-4e5c-91d2-089ac9bafe30",
                            TwoFactorEnabled = false,
                            UserName = "eric@cognizant.com"
                        },
                        new
                        {
                            Id = "ad4faee2-b1ff-4c19-bc85-2400fc2e9787",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "34a6a144-dd4c-461c-b8ab-9c8c8ea770cd",
                            Email = "ravid@cognizant.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "RAVID@COGNIZANT.COM",
                            NormalizedUserName = "RAVID@COGNIZANT.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIcWBIzr9B9JjCDyrMkw6OwRTXwTJjPRxdfKjz0ywToEC7LmylSjy6Jfq5UvzXsrng==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d18eb043-0692-4e8c-9608-d117aa3b1bc8",
                            TwoFactorEnabled = false,
                            UserName = "ravid@cognizant.com"
                        },
                        new
                        {
                            Id = "3f2b23ed-0959-45a4-9499-8b1ee1f0f4d9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "24331fc0-16b4-4646-9c02-489cad2c6865",
                            Email = "edward@cognizant.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EDWARD@COGNIZANT.COM",
                            NormalizedUserName = "EDWARD@COGNIZANT.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEItwzDM/7QIhwLZkuKPHfJGOSLgmbufJqqYilpRcOVHMR388mxXvQgYihQxkwhuTpw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a22e43d6-3132-493d-80a1-da95aff84d0c",
                            TwoFactorEnabled = false,
                            UserName = "edward@cognizant.com"
                        },
                        new
                        {
                            Id = "e03b81e4-c2be-4a64-b26d-0782511cfbc4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8ac15788-1524-402f-a4ed-2655f57fd1d6",
                            Email = "jessica@cognizant.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JESSICA@COGNIZANT.COM",
                            NormalizedUserName = "JESSICA@COGNIZANT.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKIdBO5nyMvy35w4/n6MIPScPUxm5OevmEr4LDlCpKHRnHC2tqVOSSsFraEDDTnw6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f760f24b-58af-49ab-a378-fc10cf0606e7",
                            TwoFactorEnabled = false,
                            UserName = "jessica@cognizant.com"
                        },
                        new
                        {
                            Id = "3aee0927-28c9-4308-92cc-296bf325521b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0bcce475-c117-4132-8c7c-0cb4db578665",
                            Email = "charles@cognizant.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CHARLES@COGNIZANT.COM",
                            NormalizedUserName = "CHARLES@COGNIZANT.COM",
                            ParentId = "93513a22-cecd-4bdc-ae16-c0dd5c95e4e9",
                            PasswordHash = "AQAAAAEAACcQAAAAEDbocw9EgX1+DoFcAGFt6ACKmjJXZ0xFYh7nSTqBzDoFJSINA24qlA1xswGb8JFqHQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e0f6fb49-040b-4c08-956e-518f5b37acb4",
                            TwoFactorEnabled = false,
                            UserName = "charles@cognizant.com"
                        },
                        new
                        {
                            Id = "5ac8f00d-f3bb-4c96-8570-6f8997cf2ae5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5ad151c0-a6e2-4218-b14f-911c9a41d367",
                            Email = "scott@cognizant.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SCOTT@COGNIZANT.COM",
                            NormalizedUserName = "SCOTT@COGNIZANT.COM",
                            ParentId = "93513a22-cecd-4bdc-ae16-c0dd5c95e4e9",
                            PasswordHash = "AQAAAAEAACcQAAAAEMSPMfWrbWdpJV6qDypWxt8NLqn1IYuTU1DlX0VV89Ehb2jJ63FtaBHwLnEYq9gbYQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "651f8282-bedd-4936-b6c7-8ae6bc5ca090",
                            TwoFactorEnabled = false,
                            UserName = "scott@cognizant.com"
                        });
                });

            modelBuilder.Entity("health_index_app.Server.Models.UserMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMeals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MealId = 10004,
                            Name = "Lunch",
                            UserId = "5ac8f00d-f3bb-4c96-8570-6f8997cf2ae5"
                        },
                        new
                        {
                            Id = 2,
                            MealId = 10001,
                            Name = "Snack",
                            UserId = "3f2b23ed-0959-45a4-9499-8b1ee1f0f4d9"
                        },
                        new
                        {
                            Id = 3,
                            MealId = 10005,
                            Name = "Duck",
                            UserId = "5ac8f00d-f3bb-4c96-8570-6f8997cf2ae5"
                        },
                        new
                        {
                            Id = 4,
                            MealId = 10004,
                            Name = "Worcestershire",
                            UserId = "3aee0927-28c9-4308-92cc-296bf325521b"
                        },
                        new
                        {
                            Id = 5,
                            MealId = 10003,
                            Name = "Truffle Oil",
                            UserId = "ad4faee2-b1ff-4c19-bc85-2400fc2e9787"
                        },
                        new
                        {
                            Id = 6,
                            MealId = 10004,
                            Name = "Feta",
                            UserId = "3f2b23ed-0959-45a4-9499-8b1ee1f0f4d9"
                        },
                        new
                        {
                            Id = 7,
                            MealId = 10002,
                            Name = "Fenugreek",
                            UserId = "e03b81e4-c2be-4a64-b26d-0782511cfbc4"
                        },
                        new
                        {
                            Id = 8,
                            MealId = 10006,
                            Name = "Rocket",
                            UserId = "5ac8f00d-f3bb-4c96-8570-6f8997cf2ae5"
                        });
                });

            modelBuilder.Entity("health_index_app.Shared.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ServingId")
                        .HasColumnType("int");

                    b.Property<double?>("AddedSugar")
                        .HasColumnType("float");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Calcium")
                        .HasColumnType("float");

                    b.Property<double?>("Calories")
                        .HasColumnType("float");

                    b.Property<double?>("CarboHydrate")
                        .HasColumnType("float");

                    b.Property<double?>("Cholesterol")
                        .HasColumnType("float");

                    b.Property<double?>("Fat")
                        .HasColumnType("float");

                    b.Property<double?>("Fiber")
                        .HasColumnType("float");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Iron")
                        .HasColumnType("float");

                    b.Property<string>("MeasurementDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MetricServingAmount")
                        .HasColumnType("float");

                    b.Property<string>("MetricServingUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MonounsaturatedFat")
                        .HasColumnType("float");

                    b.Property<double>("NumberOfUnits")
                        .HasColumnType("float");

                    b.Property<double?>("PolyunsaturatedFat")
                        .HasColumnType("float");

                    b.Property<double?>("Potassium")
                        .HasColumnType("float");

                    b.Property<double?>("Protein")
                        .HasColumnType("float");

                    b.Property<double?>("SaturatedFat")
                        .HasColumnType("float");

                    b.Property<string>("ServingDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServingURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Sodium")
                        .HasColumnType("float");

                    b.Property<double?>("Sugar")
                        .HasColumnType("float");

                    b.Property<double?>("VitaminA")
                        .HasColumnType("float");

                    b.Property<double?>("VitaminC")
                        .HasColumnType("float");

                    b.Property<double?>("VitaminD")
                        .HasColumnType("float");

                    b.HasKey("Id", "ServingId");

                    b.HasIndex("Id", "ServingId")
                        .IsUnique();

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 26547,
                            ServingId = 66486,
                            BrandName = "In-N-Out",
                            Calcium = 0.0,
                            Calories = 670.0,
                            CarboHydrate = 39.0,
                            Cholesterol = 120.0,
                            Fat = 39.0,
                            Fiber = 3.0,
                            FoodName = "Double-Double Burger",
                            FoodType = "Brand",
                            FoodURL = "https://www.fatsecret.com/calories-nutrition/in-n-out/double-double-burger",
                            Iron = 0.0,
                            MeasurementDescription = "serving",
                            MetricServingAmount = 330.0,
                            MetricServingUnit = "g",
                            NumberOfUnits = 0.0,
                            PolyunsaturatedFat = 0.0,
                            Potassium = 0.0,
                            Protein = 37.0,
                            SaturatedFat = 17.0,
                            ServingDescription = "1 burger",
                            ServingURL = "https://www.fatsecret.com/calories-nutrition/in-n-out/double-double-burger",
                            Sodium = 1520.0,
                            Sugar = 10.0,
                            VitaminA = 0.0,
                            VitaminC = 0.0,
                            VitaminD = 0.0
                        },
                        new
                        {
                            Id = 31818,
                            ServingId = 101820,
                            BrandName = "Dole",
                            Calcium = 0.0,
                            Calories = 15.0,
                            CarboHydrate = 4.0,
                            Cholesterol = 0.0,
                            Fat = 0.0,
                            Fiber = 1.0,
                            FoodName = "Classic Iceberg Salad",
                            FoodType = "Brand",
                            FoodURL = "https://www.fatsecret.com/calories-nutrition/dole/classic-iceberg-salad",
                            Iron = 0.0,
                            MeasurementDescription = "serving",
                            MetricServingAmount = 85.0,
                            MetricServingUnit = "g",
                            NumberOfUnits = 0.0,
                            PolyunsaturatedFat = 0.0,
                            Potassium = 0.0,
                            Protein = 1.0,
                            SaturatedFat = 0.0,
                            ServingDescription = "1 1/2 cups",
                            ServingURL = "https://www.fatsecret.com/calories-nutrition/dole/classic-iceberg-salad",
                            Sodium = 15.0,
                            Sugar = 2.0,
                            VitaminA = 0.0,
                            VitaminC = 0.0,
                            VitaminD = 0.0
                        },
                        new
                        {
                            Id = 251811,
                            ServingId = 289802,
                            BrandName = "Coors",
                            Calcium = 0.0,
                            Calories = 164.0,
                            CarboHydrate = 13.0,
                            Cholesterol = 0.0,
                            Fat = 0.0,
                            Fiber = 0.0,
                            FoodName = "Blue Moon Beer",
                            FoodType = "Brand",
                            FoodURL = "https://www.fatsecret.com/calories-nutrition/coors/blue-moon-beer",
                            Iron = 0.0,
                            MeasurementDescription = "serving",
                            MetricServingAmount = 12.0,
                            MetricServingUnit = "oz",
                            NumberOfUnits = 0.0,
                            PolyunsaturatedFat = 0.0,
                            Potassium = 0.0,
                            Protein = 2.0,
                            SaturatedFat = 0.0,
                            ServingDescription = "1 bottle",
                            ServingURL = "https://www.fatsecret.com/calories-nutrition/coors/blue-moon-beer",
                            Sodium = 8.0,
                            Sugar = 0.0,
                            VitaminA = 0.0,
                            VitaminC = 0.0,
                            VitaminD = 0.0
                        },
                        new
                        {
                            Id = 568586,
                            ServingId = 591920,
                            BrandName = "",
                            Calcium = 6.0,
                            Calories = 56.0,
                            CarboHydrate = 14.640000000000001,
                            Cholesterol = 0.0,
                            Fat = 0.17999999999999999,
                            Fiber = 2.5,
                            FoodName = "Golden Delicious Apples",
                            FoodType = "Generic",
                            FoodURL = "https://www.fatsecret.com/calories-nutrition/generic/apples-golden-delicious",
                            Iron = 0.10000000000000001,
                            MeasurementDescription = "small  (2-1/2\" dia)",
                            MetricServingAmount = 106.0,
                            MetricServingUnit = "g",
                            NumberOfUnits = 0.0,
                            PolyunsaturatedFat = 0.055,
                            Potassium = 113.0,
                            Protein = 0.27000000000000002,
                            SaturatedFat = 0.029000000000000001,
                            ServingDescription = "1 small (2-1/2\" dia)",
                            ServingURL = "https://www.fatsecret.com/calories-nutrition/generic/apples-golden-delicious",
                            Sodium = 1.0,
                            Sugar = 11.01,
                            VitaminA = 3.0,
                            VitaminC = 4.7999999999999998,
                            VitaminD = 0.0
                        },
                        new
                        {
                            Id = 2861015,
                            ServingId = 2787144,
                            BrandName = "Annie Chun's",
                            Calcium = 0.0,
                            Calories = 280.0,
                            CarboHydrate = 59.0,
                            Cholesterol = 0.0,
                            Fat = 1.0,
                            Fiber = 3.0,
                            FoodName = "Vietnamese Pho",
                            FoodType = "Brand",
                            FoodURL = "https://www.fatsecret.com/calories-nutrition/annie-chuns/vietnamese-pho",
                            Iron = 0.0,
                            MeasurementDescription = "serving",
                            MetricServingAmount = 170.0,
                            MetricServingUnit = "g",
                            NumberOfUnits = 0.0,
                            PolyunsaturatedFat = 1.0,
                            Potassium = 0.0,
                            Protein = 10.0,
                            SaturatedFat = 0.0,
                            ServingDescription = "1 bowl",
                            ServingURL = "https://www.fatsecret.com/calories-nutrition/annie-chuns/vietnamese-pho",
                            Sodium = 1030.0,
                            Sugar = 4.0,
                            VitaminA = 0.0,
                            VitaminC = 0.0,
                            VitaminD = 0.0
                        },
                        new
                        {
                            Id = 9771793,
                            ServingId = 9336939,
                            BrandName = "Suraj",
                            Calcium = 0.0,
                            Calories = 140.0,
                            CarboHydrate = 24.0,
                            Cholesterol = 0.0,
                            Fat = 3.0,
                            Fiber = 1.0,
                            FoodName = "Naan",
                            FoodType = "Brand",
                            FoodURL = "https://www.fatsecret.com/calories-nutrition/suraj/naan",
                            Iron = 0.0,
                            MeasurementDescription = "serving",
                            MetricServingAmount = 50.0,
                            MetricServingUnit = "g",
                            NumberOfUnits = 0.0,
                            PolyunsaturatedFat = 0.0,
                            Potassium = 0.0,
                            Protein = 4.0,
                            SaturatedFat = 0.5,
                            ServingDescription = "1/2 naan",
                            ServingURL = "https://www.fatsecret.com/calories-nutrition/suraj/naan",
                            Sodium = 320.0,
                            Sugar = 2.0,
                            VitaminA = 0.0,
                            VitaminC = 0.0,
                            VitaminD = 0.0
                        },
                        new
                        {
                            Id = 41321916,
                            ServingId = 36059775,
                            BrandName = "Nong Shim",
                            Calcium = 20.0,
                            Calories = 450.0,
                            CarboHydrate = 64.0,
                            Cholesterol = 5.0,
                            Fat = 18.0,
                            Fiber = 5.0,
                            FoodName = "Tonkotsu Ramen",
                            FoodType = "Brand",
                            FoodURL = "https://www.fatsecret.com/calories-nutrition/nong-shim/tonkotsu-ramen",
                            Iron = 2.2000000000000002,
                            MeasurementDescription = "serving",
                            MetricServingAmount = 101.0,
                            MetricServingUnit = "g",
                            NumberOfUnits = 0.0,
                            PolyunsaturatedFat = 3.0,
                            Potassium = 380.0,
                            Protein = 8.0,
                            SaturatedFat = 7.0,
                            ServingDescription = "1 container",
                            ServingURL = "https://www.fatsecret.com/calories-nutrition/nong-shim/tonkotsu-ramen",
                            Sodium = 1550.0,
                            Sugar = 5.0,
                            VitaminA = 0.0,
                            VitaminC = 0.0,
                            VitaminD = 0.0
                        },
                        new
                        {
                            Id = 91707,
                            ServingId = 132185,
                            BrandName = "Wylwood",
                            Calcium = 0.0,
                            Calories = 30.0,
                            CarboHydrate = 6.0,
                            Cholesterol = 0.0,
                            Fat = 0.0,
                            Fiber = 2.0,
                            FoodName = "Stir Fry Vegetables",
                            FoodType = "Brand",
                            FoodURL = "https://www.fatsecret.com/calories-nutrition/wylwood/stir-fry-vegetables",
                            Iron = 0.0,
                            MeasurementDescription = "serving",
                            MetricServingAmount = 75.0,
                            MetricServingUnit = "g",
                            NumberOfUnits = 0.0,
                            PolyunsaturatedFat = 0.0,
                            Potassium = 0.0,
                            Protein = 2.0,
                            SaturatedFat = 0.0,
                            ServingDescription = "3/4 cup",
                            ServingURL = "https://www.fatsecret.com/calories-nutrition/wylwood/stir-fry-vegetables",
                            Sodium = 15.0,
                            Sugar = 3.0,
                            VitaminA = 0.0,
                            VitaminC = 0.0,
                            VitaminD = 0.0
                        },
                        new
                        {
                            Id = 1921249,
                            ServingId = 1886238,
                            BrandName = "Assi",
                            Calcium = 0.0,
                            Calories = 123.0,
                            CarboHydrate = 15.0,
                            Cholesterol = 0.0,
                            Fat = 3.1000000000000001,
                            Fiber = 5.0,
                            FoodName = "Curry",
                            FoodType = "Brand",
                            FoodURL = "https://www.fatsecret.com/calories-nutrition/assi/curry",
                            Iron = 0.0,
                            MeasurementDescription = "serving",
                            MetricServingAmount = 180.0,
                            MetricServingUnit = "g",
                            NumberOfUnits = 0.0,
                            PolyunsaturatedFat = 0.0,
                            Potassium = 0.0,
                            Protein = 3.0,
                            SaturatedFat = 2.0,
                            ServingDescription = "1 serving",
                            ServingURL = "https://www.fatsecret.com/calories-nutrition/assi/curry",
                            Sodium = 802.0,
                            Sugar = 6.0,
                            VitaminA = 0.0,
                            VitaminC = 0.0,
                            VitaminD = 0.0
                        });
                });

            modelBuilder.Entity("health_index_app.Shared.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("HealthIndex")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            HealthIndex = 5.0
                        },
                        new
                        {
                            Id = 10002,
                            HealthIndex = 3.0
                        },
                        new
                        {
                            Id = 10003,
                            HealthIndex = 7.0
                        },
                        new
                        {
                            Id = 10004,
                            HealthIndex = 10.0
                        },
                        new
                        {
                            Id = 10005,
                            HealthIndex = 1.0
                        },
                        new
                        {
                            Id = 10006,
                            HealthIndex = 6.0
                        });
                });

            modelBuilder.Entity("health_index_app.Shared.Models.MealFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("ServingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("FoodId", "ServingId");

                    b.ToTable("MealFoods");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "adf3001d-64d3-4dfb-b93f-3ad2503167e7",
                            ConcurrencyStamp = "87babb54-c603-4b8e-a08c-85cde78c78ba",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "93513a22-cecd-4bdc-ae16-c0dd5c95e4e9",
                            RoleId = "adf3001d-64d3-4dfb-b93f-3ad2503167e7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("health_index_app.Server.Models.ApplicationUser", b =>
                {
                    b.HasOne("health_index_app.Server.Models.ApplicationUser", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("health_index_app.Server.Models.UserMeal", b =>
                {
                    b.HasOne("health_index_app.Shared.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("health_index_app.Server.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("health_index_app.Shared.Models.MealFood", b =>
                {
                    b.HasOne("health_index_app.Shared.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("health_index_app.Shared.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId", "ServingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("health_index_app.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("health_index_app.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("health_index_app.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("health_index_app.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
